// Generated by CoffeeScript 1.3.3
(function() {
  var ActionMethods,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  module.exports = ActionMethods = (function() {

    function ActionMethods(apiClient) {
      this.apiClient = apiClient;
      this.post = __bind(this.post, this);

      if (!this.apiClient) {
        throw new Error("apiClient parameter is required");
      }
    }

    ActionMethods.prototype.post = function(actAsActorId, cb) {
      if (actAsActorId == null) {
        actAsActorId = null;
      }
      if (cb == null) {
        cb = function() {};
      }
      return this.apiClient.post("/actions/setup-new-user", {}, actAsActorId, cb);
    };

    return ActionMethods;

  })();

}).call(this);
