// Generated by CoffeeScript 1.3.3
(function() {
  var ChannelMethods,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  module.exports = ChannelMethods = (function() {

    function ChannelMethods(apiClient) {
      this.apiClient = apiClient;
      this.get = __bind(this.get, this);

      if (!this.apiClient) {
        throw new Error("apiClient parameter is required");
      }
    }

    ChannelMethods.prototype.get = function(channelId, cb) {
      if (cb == null) {
        cb = function() {};
      }
      return this.apiClient.get("/channels/" + channelId, null, null, cb);
    };

    return ChannelMethods;

  })();

}).call(this);
