// Generated by CoffeeScript 1.4.0
(function() {
  var CommentMethods,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  module.exports = CommentMethods = (function() {

    function CommentMethods(apiClient) {
      this.apiClient = apiClient;
      this.get = __bind(this.get, this);

      if (!this.apiClient) {
        throw new Error("apiClient parameter is required");
      }
    }

    CommentMethods.prototype.get = function(commentId, options, cb) {
      if (options == null) {
        options = {};
      }
      if (cb == null) {
        cb = function() {};
      }
      if (!commentId) {
        return cb(new Error("Parameter commentId required."));
      }
      return this.apiClient.get("/comments/" + commentId, options.params, options.actAsActorId, cb);
    };

    return CommentMethods;

  })();

}).call(this);
