// Generated by CoffeeScript 1.3.3
(function() {
  var StylistMethods,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  module.exports = StylistMethods = (function() {

    function StylistMethods(apiClient) {
      this.apiClient = apiClient;
      this["delete"] = __bind(this["delete"], this);

      this.put = __bind(this.put, this);

      this.patch = __bind(this.patch, this);

      this.post = __bind(this.post, this);

      this.get = __bind(this.get, this);

      this.all = __bind(this.all, this);

      if (!this.apiClient) {
        throw new Error("apiClient parameter is required");
      }
    }

    StylistMethods.prototype.all = function(params, actAsActorId, cb) {
      if (params == null) {
        params = {};
      }
      if (actAsActorId == null) {
        actAsActorId = null;
      }
      if (cb == null) {
        cb = function() {};
      }
      return this.apiClient.get("/stylists", params, actAsActorId, cb);
    };

    StylistMethods.prototype.get = function(stylistId, params, actAsActorId, cb) {
      if (params == null) {
        params = {};
      }
      if (actAsActorId == null) {
        actAsActorId = null;
      }
      if (cb == null) {
        cb = function() {};
      }
      return this.apiClient.get("/stylists/" + stylistId, params, actAsActorId, cb);
    };

    StylistMethods.prototype.post = function(data, actAsActorId, cb) {
      if (data == null) {
        data = {};
      }
      if (actAsActorId == null) {
        actAsActorId = null;
      }
      if (cb == null) {
        cb = function() {};
      }
      return this.apiClient.post("/stylists", data, actAsActorId, cb);
    };

    StylistMethods.prototype.patch = function(stylistId, data, actAsActorId, cb) {
      if (data == null) {
        data = {};
      }
      if (actAsActorId == null) {
        actAsActorId = null;
      }
      if (cb == null) {
        cb = function() {};
      }
      return this.apiClient.patch("/stylists/" + stylistId, data, actAsActorId, cb);
    };

    StylistMethods.prototype.put = function(stylistId, data, actAsActorId, cb) {
      if (data == null) {
        data = {};
      }
      if (actAsActorId == null) {
        actAsActorId = null;
      }
      if (cb == null) {
        cb = function() {};
      }
      return this.apiClient.put("/stylists/" + stylistId, data, actAsActorId, cb);
    };

    StylistMethods.prototype["delete"] = function(stylistId, actAsActorId, cb) {
      if (actAsActorId == null) {
        actAsActorId = null;
      }
      if (cb == null) {
        cb = function() {};
      }
      return this.apiClient["delete"]("/stylists/" + stylistId, null, actAsActorId, cb);
    };

    return StylistMethods;

  })();

}).call(this);
