// Generated by CoffeeScript 1.4.0
(function() {
  var UserMethods,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  module.exports = UserMethods = (function() {

    function UserMethods(apiClient) {
      this.apiClient = apiClient;
      this.getStats = __bind(this.getStats, this);

      this.getStyleEvents = __bind(this.getStyleEvents, this);

      if (!this.apiClient) {
        throw new Error("apiClient parameter is required");
      }
    }

    UserMethods.prototype.getStyleEvents = function(userId, params, actAsActorId, cb) {
      if (params == null) {
        params = {};
      }
      if (actAsActorId == null) {
        actAsActorId = null;
      }
      if (cb == null) {
        cb = function() {};
      }
      return this.apiClient.get("/users/" + userId + "/style-events", params, actAsActorId, cb);
    };

    UserMethods.prototype.getStats = function(userId, params, actAsActorId, cb) {
      if (params == null) {
        params = {};
      }
      if (actAsActorId == null) {
        actAsActorId = null;
      }
      if (cb == null) {
        cb = function() {};
      }
      return this.apiClient.get("/users/" + userId + "/stats", params, actAsActorId, cb);
    };

    return UserMethods;

  })();

}).call(this);
